#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d 1 2 3 4 5 6 7 8 9 0 

############Window Settings ####################
bspc config border_width         1
bspc config window_gap           5 
bspc config focus_follows_pointer	true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      true
bspc config top_padding 	 20

########## Border Colors #################
bspc config focused_border_color "#353b45"
bspc config normal_border_color "#353b45"

######### Program settings ################
bspc rule -a spotify ='^5' 
bspc rule -a TelegramDesktop desktop='^4'
bspc rule -a Firefox desktop='^2'
bspc rule -a Zathura state=tiled 
dunst &

######### Other Settings ################
xsetroot -cursor_name left_ptr &

######### My Bar ###############
~/.config/polybar/launch.sh --cuts
#polybar -r example 2>&1
#polybar example -c ~/.config/polybar/config.ini
